<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class GameRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'title' => 'required|string',
            'description' => 'required|string|min:50',
            'genre_id' => '',
            'image' => '',
            'price' => 'integer'
        ];
    }

    public function validated($key = null, $default = null)
    {
        $data = parent::validated($key, $default); // TODO: Change the autogenerated stub
        $data['image'] = $this->createPathForImage();
        return $data;
    }

    private function createPathForImage() : ?string
    {
        if ($this->hasFile('image')){
            return $this->file('image')->store('images', 'public');
        }
        return asset('images/image.jpg');
    }
}
